### ISSUE TITLE
Build failed for PR: #304, ffmpeg commandline utility stdout output to Appendable

### ISSUE THREAD

**Issue by mahesh-observe** [bramp/ffmpeg-cli-wrapper#328] opened 2024-04-29 08:29 UTC
**Describe the bug**

Build failed for PR: #304

 ffmpeg commandline utility stdout output to Appendable

**Comment by Euklios** [comment] 2024-05-07 08:22
Sorry for you to encounter this issue.
What exactly is failing for you?
Building the library should still work fine, note that `maven-gpg-plugin` will fail, if the system is not configured for it and is expected.

If your issue relates to your code, could you please share how you're using this library?

**Comment by Euklios** [comment] 2024-08-08 13:17
@mahesh-observe I'm currently unable to reproduce this issue, so I will close it for now.
If the issue still persists, please re-open and add information such as: Command you are executing, logs, or anything else that might be useful to reproduce

**Closed by Euklios** 2024-08-08 13:17 UTC
Labels: bug
