### ISSUE TITLE
 java.lang.ClassNotFoundException: com.google.common.base.MoreObjects

### ISSUE THREAD

**Issue by yeahbutwalter** [bramp/ffmpeg-cli-wrapper#70] opened 2016-10-24 22:36 UTC
Using v0.5 I get the following stack trace

24-Oct-2016 15:31:20.778 SEVERE [http-apr-8082-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jerseyspring] in context with path [] threw exception [java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects] with root cause
 java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1332)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
    at net.bramp.ffmpeg.FFmpeg.<clinit>(FFmpeg.java:37)
    at com.foo.service.VideoServiceFFmpegCli.init(VideoServiceFFmpegCli.java:73)
    at com.foo.rest.UploadResource2.upload(UploadResource2.java:333)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.foo.filter.TokenFilter.doFilter(TokenFilter.java:98)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.foo.filter.CorsFilter2.doFilter(CorsFilter2.java:34)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

Explicitly adding guava resolves the issue.

<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
 </dependency>

**Comment by bramp** [comment] 2016-10-24 22:48
How did you include ffmpeg-cli-wrapper into your code? Did you use Maven, or use the ffmpeg-cli-wrapper Jar directly?

**Comment by yeahbutwalter** [comment] 2016-10-24 23:07
Maven. Bombs without explicit guava dependency.

` <dependency>
            <groupId>net.bramp.ffmpeg</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>0.5</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
        </dependency>`

**Comment by bramp** [comment] 2016-10-25 03:24
So I'm unsure why you would seeing this problem. The pom.xml for the project defines guava as a dependency: https://github.com/bramp/ffmpeg-cli-wrapper/blob/ffmpeg-0.5/pom.xml#L64

MoreObjects wasn't available in Guava until version 18.0. Is your project perhaps using a older version of Guava? Or is there some other reason Maven isn't pulling in ffmpeg-cli-wrapper's dependencies?

Could you provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/)?

**Comment by yeahbutwalter** [comment] 2016-11-11 00:36
I would have to provide my entire project. Not really doable. It works when I explicitly add guava dependency so I'm happy

**Comment by bramp** [comment] 2016-11-11 03:43
Would you mind removing your explicit guava dependency, confirm that you still get the NoClassDef error, and then send me the output of `mvn dependency:tree -Dverbose`.

**Comment by yeahbutwalter** [comment] 2016-11-11 20:30
Removed the dependency, still get NoClassDefError at runtime, Here's the output:

C:\projects\foo-services>mvn dependency:tree -Dverbose
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom (21 KB at 26.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.jar (122 KB at 572.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (5 KB at 49.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom (12 KB at 109.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar (24 KB at 161.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 KB at 123.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (13 KB at 106.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (204 KB at 643.4 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building foo-services 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ foo-services ---
[INFO] com.foo:foo-services:war:1.0-SNAPSHOT
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.6.4:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.6.4:compile
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.6.4:compile - omitted for duplicate)
[INFO] |  \- (log4j:log4j:jar:1.2.16:compile - omitted for conflict with 1.2.17)
[INFO] +- org.springframework:spring-core:jar:4.2.1.RELEASE:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.springframework:spring-context:jar:4.2.1.RELEASE:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- org.springframework:spring-beans:jar:4.2.1.RELEASE:compile
[INFO] |  |  \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- org.springframework:spring-expression:jar:4.2.1.RELEASE:compile
[INFO] |     \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-context-support:jar:4.2.1.RELEASE:compile
[INFO] |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- org.javassist:javassist:jar:3.17.1-GA:compile
[INFO] +- org.springframework:spring-test:jar:4.2.1.RELEASE:test
[INFO] |  \- (org.springframework:spring-core:jar:4.2.1.RELEASE:test - omitted for duplicate)
[INFO] +- junit:junit:jar:4.12:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- org.codehaus.enunciate:enunciate-core-annotations:jar:1.31:compile
[INFO] |  \- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] +- postgresql:postgresql:jar:9.1-901.jdbc4:compile
[INFO] +- org.springframework:spring-orm:jar:4.2.1.RELEASE:compile
[INFO] |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- org.springframework:spring-jdbc:jar:4.2.1.RELEASE:compile
[INFO] |  |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  |  +- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  |  \- (org.springframework:spring-tx:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- org.springframework:spring-tx:jar:4.2.1.RELEASE:compile
[INFO] |     +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |     \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- com.jolbox:bonecp:jar:0.8.0.RELEASE:compile
[INFO] |  +- com.google.guava:guava:jar:15.0:compile
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.2:compile - omitted for conflict with 1.6.4)
[INFO] +- org.springframework:spring-web:jar:4.2.1.RELEASE:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- com.sun.jersey.contribs:jersey-spring:jar:1.19.1:compile
[INFO] |  \- com.sun.jersey:jersey-servlet:jar:1.19.1:compile
[INFO] |     \- com.sun.jersey:jersey-server:jar:1.19.1:compile
[INFO] |        \- (com.sun.jersey:jersey-core:jar:1.19.1:compile - omitted for duplicate)
[INFO] +- com.sun.jersey:jersey-json:jar:1.19.1:compile
[INFO] |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO] |  |  \- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO] |  |     +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |     \- (javax.activation:activation:jar:1.1:compile - omitted for duplicate)
[INFO] |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile
[INFO] |  |  \- (org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.2:compile
[INFO] |  |  +- (org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  |  \- (org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  +- org.codehaus.jackson:jackson-xc:jar:1.9.2:compile
[INFO] |  |  +- (org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  |  \- (org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  \- com.sun.jersey:jersey-core:jar:1.19.1:compile
[INFO] |     \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] +- com.sun.jersey.contribs:jersey-multipart:jar:1.19.1:compile
[INFO] |  +- org.jvnet.mimepull:mimepull:jar:1.9.3:compile
[INFO] |  \- (com.sun.jersey:jersey-core:jar:1.19.1:compile - omitted for duplicate)
[INFO] +- com.sun.jersey:jersey-client:jar:1.19.1:compile
[INFO] |  \- (com.sun.jersey:jersey-core:jar:1.19.1:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-webmvc:jar:4.2.1.RELEASE:compile
[INFO] |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-expression:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-web:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework.security:spring-security-core:jar:3.2.5.RELEASE:compile
[INFO] |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- (org.springframework:spring-aop:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-beans:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-context:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-core:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  \- (org.springframework:spring-expression:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] +- org.springframework.security:spring-security-web:jar:3.2.5.RELEASE:compile
[INFO] |  +- (aopalliance:aopalliance:jar:1.0:compile - omitted for duplicate)
[INFO] |  +- (org.springframework.security:spring-security-core:jar:3.2.5.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-context:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-core:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-expression:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  \- (org.springframework:spring-web:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] +- org.springframework.security:spring-security-config:jar:3.2.5.RELEASE:compile
[INFO] |  +- (aopalliance:aopalliance:jar:1.0:compile - omitted for duplicate)
[INFO] |  +- (org.springframework.security:spring-security-core:jar:3.2.5.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-aop:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-beans:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-context:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  \- (org.springframework:spring-core:jar:3.2.8.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[INFO] +- cglib:cglib:jar:2.2.2:compile
[INFO] |  \- asm:asm:jar:3.3.1:compile
[INFO] +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] +- com.drewnoakes:metadata-extractor:jar:2.9.1:compile
[INFO] |  \- com.adobe.xmp:xmpcore:jar:5.1.2:compile
[INFO] +- org.apache.tika:tika-core:jar:1.4:compile
[INFO] +- org.springframework.data:spring-data-solr:jar:1.3.2.RELEASE:compile
[INFO] |  +- (org.springframework:spring-context:jar:4.0.9.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- (org.springframework:spring-tx:jar:4.0.9.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.9.2.RELEASE:compile
[INFO] |  |  +- (org.springframework:spring-core:jar:4.0.9.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  |  +- (org.springframework:spring-beans:jar:4.0.9.RELEASE:compile - omitted for conflict with 4.2.1.RELEASE)
[INFO] |  |  +- (org.slf4j:slf4j-api:jar:1.7.10:compile - omitted for conflict with 1.6.4)
[INFO] |  |  \- (org.slf4j:jcl-over-slf4j:jar:1.7.10:runtime - omitted for duplicate)
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.1:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.2.6:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.2.5:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.2.6:compile
[INFO] |  |  \- (org.apache.httpcomponents:httpcore:jar:4.2.5:compile - omitted for duplicate)
[INFO] |  +- org.apache.httpcomponents:httpclient-cache:jar:4.2.6:compile
[INFO] |  |  \- (org.apache.httpcomponents:httpclient:jar:4.2.6:compile - omitted for duplicate)
[INFO] |  +- org.apache.solr:solr-solrj:jar:4.7.2:compile
[INFO] |  |  +- (commons-io:commons-io:jar:2.1:compile - omitted for conflict with 2.4)
[INFO] |  |  +- (log4j:log4j:jar:1.2.16:compile - omitted for conflict with 1.2.17)
[INFO] |  |  +- (org.apache.httpcomponents:httpcore:jar:4.3:compile - omitted for conflict with 4.2.5)
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.5:compile
[INFO] |  |  +- org.codehaus.woodstox:wstx-asl:jar:3.2.7:compile
[INFO] |  |  \- org.noggit:noggit:jar:0.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.4.5:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile - omitted for conflict with 2.5.3)
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.4.5:compile
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.10:compile - omitted for conflict with 1.6.4)
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.10:runtime
[INFO] |     \- (org.slf4j:slf4j-api:jar:1.7.10:runtime - omitted for conflict with 1.6.4)
[INFO] +- net.coobird:thumbnailator:jar:0.4.8:compile
[INFO] +- org.springframework:spring-aop:jar:4.2.1.RELEASE:compile
[INFO] |  +- (aopalliance:aopalliance:jar:1.0:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.2.1.RELEASE:compile - omitted for duplicate)
[INFO] +- org.aspectj:aspectjrt:jar:1.6.11:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.6.11:compile
[INFO] +- org.apache.commons:commons-exec:jar:1.2:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- javax.mail:mail:jar:1.4.7:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- joda-time:joda-time:jar:2.9.1:compile
[INFO] +- org.joda:joda-convert:jar:1.8.1:compile
[INFO] +- com.stripe:stripe-java:jar:2.5.0:compile
[INFO] |  \- (com.google.code.gson:gson:jar:2.2.4:compile - omitted for duplicate)
[INFO] +- com.github.fernandospr:javapns-jdk16:jar:2.4.0:compile
[INFO] |  \- (log4j:log4j:jar:1.2.12:compile - omitted for conflict with 1.2.17)
[INFO] +- org.apache.sanselan:sanselan:jar:0.97-incubator:compile
[INFO] +- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.3:compile
[INFO] +- com.ganyo:gcm-server:jar:1.0.2:compile
[INFO] |  \- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] +- com.google.code.geocoder-java:geocoder-java:jar:0.16:compile
[INFO] |  +- (com.google.code.gson:gson:jar:2.2.4:compile - omitted for duplicate)
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.7:compile - omitted for conflict with 1.6.4)
[INFO] |  \- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |     +- (commons-logging:commons-logging:jar:1.0.4:compile - omitted for conflict with 1.2)
[INFO] |     \- (commons-codec:commons-codec:jar:1.2:compile - omitted for conflict with 1.6)
[INFO] +- org.jcodec:jcodec-javase:jar:0.2.0:compile
[INFO] +- org.jcodec:jcodec:jar:0.2.0:compile
[INFO] +- org.owasp:csrfguard:jar:3.0.0:compile
[INFO] \- net.bramp.ffmpeg:ffmpeg:jar:0.5:compile
[INFO]    +- (org.slf4j:slf4j-api:jar:1.7.18:compile - omitted for conflict with 1.6.4)
[INFO]    +- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 15.0)
[INFO]    +- (commons-io:commons-io:jar:2.4:compile - omitted for duplicate)
[INFO]    +- (org.apache.commons:commons-lang3:jar:3.4:compile - omitted for conflict with 3.1)
[INFO]    +- (com.google.code.gson:gson:jar:2.6.2:compile - omitted for conflict with 2.2.4)
[INFO]    \- org.modelmapper:modelmapper:jar:0.7.5:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.403 s
[INFO] Finished at: 2016-11-11T12:27:20-08:00
[INFO] Final Memory: 18M/142M
[INFO] ------------------------------------------------------------------------

C:\projects\foo-services>

**Comment by bramp** [comment] 2016-11-11 20:51
Awesome, that was super helpful. So the root cause is this:
```
...
[INFO] +- com.jolbox:bonecp:jar:0.8.0.RELEASE:compile
[INFO] | +- com.google.guava:guava:jar:15.0:compile
...
[INFO] +- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 15.0)
...
```

Because com.jolbox:bonecp depends on v15, that is the version maven used. We need v18 or higher. I don't know enough about Maven to understand the conflict resolution rules, but I suspect either bonecp, or myself could change something to force the higher version.

I will leave this bug open to see if I can resolve this within our pom.xml.

**Comment by yeahbutwalter** [comment] 2016-11-11 22:48
I should have spotted that. Thanks for taking the time and thank you again for an awesome wrapper!

**Comment by bramp** [comment] 2016-11-12 17:19
Ok, after reading up on Maven, there seems to be no way for me (as the library owner) to fix this. It is up to the consumer to ensure all the dependencies are correctly resolved in their project.

**Closed by bramp** 2016-11-12 17:19 UTC
Labels: bug
